include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    directives_ordering: true
    omit_local_variable_types: false
    prefer_interpolation_to_compose_strings: true
    prefer_relative_imports: true
    prefer_typing_uninitialized_variables: true
    unnecessary_brace_in_string_interps: true