name: win32
description: A sample Win32 application.
version: 1.0.0
# homepage: https://www.example.com
author: Tim Sneath <timsneath@google.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
