name: win32
description: A Dart library for accessing common Win32 APIs using FFI. No C required!
version: 1.8.0-nullsafety.1
homepage: https://timsneath.github.io/win32/
repository: https://github.com/timsneath/win32
issue_tracker: https://github.com/timsneath/win32/issues
documentation: https://timsneath.github.io/win32/

environment:
  sdk: '>=2.11.0 <2.12.0'

dependencies:
  ffi: 
    git: 
      url: git@github.com:dart-lang/ffi.git
      ref: null_safety

dev_dependencies:
  lint: ^1.4.0-dev.d210.1
  test: ^1.16.0-nullsafety.5

# Cannot be published until NNBD is stable.
publish_to: none