name: win32
description: A Dart library for accessing common Win32 APIs using FFI. No C required!
version: 2.0.0-nullsafety.0
homepage: https://timsneath.github.io/win32/
repository: https://github.com/timsneath/win32
issue_tracker: https://github.com/timsneath/win32/issues
documentation: https://timsneath.github.io/win32/

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  ffi: 
    git: 
      url: https://github.com/mit-mit/ffi.git
      ref: 212nullsafety

dev_dependencies:
  lint: ^1.4.0-dev.d210.1
  test: ^1.16.0-nullsafety.9

# Cannot be published until FFI has released a null-safe version.
publish_to: none