name: win32
description: A Dart library for accessing common Win32 APIs using FFI. No C required!
version: 2.0.0-nullsafety.7
homepage: https://win32.pub
repository: https://github.com/timsneath/win32
issue_tracker: https://github.com/timsneath/win32/issues
documentation: https://win32.pub

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  ffi: ^0.2.0-nullsafety.1

dev_dependencies:
  build_runner: ^1.10.6
  json_annotation: ^3.1.1
  json_serializable: ^3.5.0
  lint: ^1.5.1
  test: ^1.16.0-nullsafety.12
  