name: explorer
description: Drive explorer, built with Flutter

version: 1.0.0+1

environment:
  sdk: '>=2.12.0-0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  win32:
    path: ../../

dev_dependencies:
  lint: ^1.4.0-dev.d210.1

## This package is not intended for publishing; it's just an example.
publish_to: none